# Generated by Django 4.0.6 on 2022-07-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Subscription name')),
                ('cost', models.IntegerField(verbose_name='Subscription cost')),
                ('distributor', models.CharField(max_length=50, verbose_name='Subscription distributor')),
                ('start_date', models.DateField(verbose_name='Subscription date')),
            ],
            options={
                'verbose_name': 'Sub',
                'verbose_name_plural': 'Subs',
            },
        ),
    ]
