# Generated by Django 4.0.6 on 2022-07-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subs',
        ),
    ]
