# Generated by Django 4.0.6 on 2022-07-13 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subs', '0002_delete_subs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Subscription name')),
                ('cost', models.IntegerField(verbose_name='Subscription cost')),
                ('distributor', models.CharField(max_length=50, verbose_name='Subscription distributor')),
                ('start_date', models.DateField(verbose_name='Subscription date')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub',
                'verbose_name_plural': 'Subs',
            },
        ),
    ]
