# Generated by Django 4.0.6 on 2022-07-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subs',
            name='username',
        ),
    ]
