# Generated by Django 4.0.6 on 2022-07-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0006_alter_subs_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='username',
            field=models.CharField(blank=True, default='users.User', max_length=50, null=True, verbose_name='users.User'),
        ),
    ]
