# Generated by Django 4.0.6 on 2022-07-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0007_alter_subs_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subs',
        ),
    ]
